name: r_expense
description: "A comprehensive, privacy-focused personal expense tracking application built with Flutter. Organize your finances with a hierarchical category system, visualize spending patterns through insightful charts, and securely backup your data to Google Drive."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flex_color_scheme: ^8.4.0
  drift: ^2.30.0
  sqlite3_flutter_libs: ^0.5.41
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_riverpod: ^2.6.1
  gap: ^3.0.1
  flutter_svg: ^2.2.3
  logger: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.30.0
  build_runner: ^2.10.4

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/fredoka/Fredoka-Light.ttf
          weight: 300
        - asset: assets/fonts/fredoka/Fredoka-Regular.ttf
          weight: 400
        - asset: assets/fonts/fredoka/Fredoka-Medium.ttf
          weight: 500
        - asset: assets/fonts/fredoka/Fredoka-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/fredoka/Fredoka-Bold.ttf
          weight: 700

  assets:
    - assets/images/icons/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
